### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by gmeans** [googleanalytics/gav4-python#1]
```
Collecting gav4
  Using cached gav4-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0v/3p70h76d5_vb45_v6bdcg2mw0000gn/T/pip-build-QiZ_7O/gav4/setup.py", line 25, in <module>
        with open(os.path.join(here, 'README.md')) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/0v/3p70h76d5_vb45_v6bdcg2mw0000gn/T/pip-build-QiZ_7O/gav4/README.md'
```

I've tried this with python 2.7 and 3.5. I'm able to install via pip using the git repo however. Is the PyPI release not up to date?

Thanks!

**Comment by mcohoon** [comment]
Fixed Thanks for reporting. Try installing 0.1.2.
